version: '3'
services:
  chrome:
    image: 'selenium/node-chrome:latest'
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1
      - SE_VNC_VIEW_ONLY=1
  video:
    image: 'selenium/video:latest'
    volumes:
      - '../results/_docker/firstTest/2023_06_08T12_19_46_359/videos:/videos'
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - FILE_NAME=firstTest.mp4
